# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: SpaceX API Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 16 * * *' # cron expression syntax: ' min | hour | day of month | month | day of week ' in UTC (this is daily @ 8AM PST)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-17-jre   
        ALLURE_VERSION="2.27.0"
        ALLURE_HOME="/opt/allure-report" # Define a system-wide home location
        curl -o allure.tgz -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz
        tar -zxvf allure.tgz
        sudo mv allure-${ALLURE_VERSION} ${ALLURE_HOME}
        echo "${ALLURE_HOME}/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest --alluredir allure-results
    - name: Generate allure report
      run: | 
         allure generate allure-results
    - name: Upload Allure Report Artifact
      uses: actions/upload-pages-artifact@v3
      with:
          name: github-pages
          path: allure-report
  deploy-report:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      needs: build
      runs-on: ubuntu-latest

      steps:
       - name: Deploy to GitHub pages
         id: deployment
         uses: actions/deploy-pages@v4
